// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Checker } from "./tables/Checker.sol";
import { Generic } from "./tables/Generic.sol";
import { Inventory } from "./tables/Inventory.sol";
import { Item } from "./tables/Item.sol";
import { Hero, HeroData } from "./tables/Hero.sol";
import { Health } from "./tables/Health.sol";
import { Attack } from "./tables/Attack.sol";
