// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EntitySystem } from "../../EntitySystem.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type EntitySystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "ggg", name: "EntitySystem" }))
EntitySystemType constant entitySystem = EntitySystemType.wrap(
  0x73796767670000000000000000000000456e7469747953797374656d00000000
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title EntitySystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library EntitySystemLib {
  error EntitySystemLib_CallingFromRootSystem();

  function create(
    EntitySystemType self,
    uint256 entityId,
    uint256[] memory componentIds,
    bytes[] memory data
  ) internal {
    return CallWrapper(self.toResourceId(), address(0)).create(entityId, componentIds, data);
  }

  function compose(EntitySystemType self, uint256 entityId, uint256 componentId, bytes memory data) internal {
    return CallWrapper(self.toResourceId(), address(0)).compose(entityId, componentId, data);
  }

  function create(
    CallWrapper memory self,
    uint256 entityId,
    uint256[] memory componentIds,
    bytes[] memory data
  ) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert EntitySystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _create_uint256_uint256Array_bytesArray.create,
      (entityId, componentIds, data)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function compose(CallWrapper memory self, uint256 entityId, uint256 componentId, bytes memory data) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert EntitySystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_compose_uint256_uint256_bytes.compose, (entityId, componentId, data));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function create(
    RootCallWrapper memory self,
    uint256 entityId,
    uint256[] memory componentIds,
    bytes[] memory data
  ) internal {
    bytes memory systemCall = abi.encodeCall(
      _create_uint256_uint256Array_bytesArray.create,
      (entityId, componentIds, data)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function compose(RootCallWrapper memory self, uint256 entityId, uint256 componentId, bytes memory data) internal {
    bytes memory systemCall = abi.encodeCall(_compose_uint256_uint256_bytes.compose, (entityId, componentId, data));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(EntitySystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(EntitySystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(EntitySystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(EntitySystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(EntitySystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (EntitySystemType) {
    return EntitySystemType.wrap(resourceId.unwrap());
  }

  function getAddress(EntitySystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _create_uint256_uint256Array_bytesArray {
  function create(uint256 entityId, uint256[] memory componentIds, bytes[] memory data) external;
}

interface _compose_uint256_uint256_bytes {
  function compose(uint256 entityId, uint256 componentId, bytes memory data) external;
}

using EntitySystemLib for EntitySystemType global;
using EntitySystemLib for CallWrapper global;
using EntitySystemLib for RootCallWrapper global;
