// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { HealthSystem } from "../../HealthSystem.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type HealthSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "ggg", name: "HealthSystem" }))
HealthSystemType constant healthSystem = HealthSystemType.wrap(
  0x737967676700000000000000000000004865616c746853797374656d00000000
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title HealthSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library HealthSystemLib {
  error HealthSystemLib_CallingFromRootSystem();

  function addHealth(HealthSystemType self, uint256 entityId, uint256 amount) internal {
    return CallWrapper(self.toResourceId(), address(0)).addHealth(entityId, amount);
  }

  function removeHealth(HealthSystemType self, uint256 entityId, uint256 amount) internal {
    return CallWrapper(self.toResourceId(), address(0)).removeHealth(entityId, amount);
  }

  function addHealth(CallWrapper memory self, uint256 entityId, uint256 amount) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert HealthSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_addHealth_uint256_uint256.addHealth, (entityId, amount));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function removeHealth(CallWrapper memory self, uint256 entityId, uint256 amount) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert HealthSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_removeHealth_uint256_uint256.removeHealth, (entityId, amount));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function addHealth(RootCallWrapper memory self, uint256 entityId, uint256 amount) internal {
    bytes memory systemCall = abi.encodeCall(_addHealth_uint256_uint256.addHealth, (entityId, amount));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function removeHealth(RootCallWrapper memory self, uint256 entityId, uint256 amount) internal {
    bytes memory systemCall = abi.encodeCall(_removeHealth_uint256_uint256.removeHealth, (entityId, amount));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(HealthSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(HealthSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(HealthSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(HealthSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(HealthSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (HealthSystemType) {
    return HealthSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(HealthSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _addHealth_uint256_uint256 {
  function addHealth(uint256 entityId, uint256 amount) external;
}

interface _removeHealth_uint256_uint256 {
  function removeHealth(uint256 entityId, uint256 amount) external;
}

using HealthSystemLib for HealthSystemType global;
using HealthSystemLib for CallWrapper global;
using HealthSystemLib for RootCallWrapper global;
