// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IEntitySystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IEntitySystem {
  function ggg__create(uint256 entityId, uint256[] memory componentIds, bytes[] memory data) external;

  function ggg__compose(uint256 entityId, uint256 componentId, bytes memory data) external;
}
