// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IHealthSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IHealthSystem {
  function ggg__addHealth(uint256 entityId, uint256 amount) external;

  function ggg__removeHealth(uint256 entityId, uint256 amount) external;
}
